### ISSUE TITLE
distribution of SPN at alt prod'y scenarios

### ISSUE THREAD

**Issue by ann-marieH** [CamFreshwater/synchSalmon#7]
from ppt to salmon MSE WG:
- lowest prod'y (fat tail/student t) - seems to have wider range of outcomes than the low prod'y (skewed dist'n)
  - I'm guessing this is b/c the mean alpha is the same with fat tail & reference? but lower with skewed?
  - how anomalous are the higher end SPN results in all instances? ... or maybe more relevant: how do the higher end/dist'n of total recruits compare?
    - e.g. plot against historical time series? (min/max + quartiles)

...current musings. will undoubtedly have more when I get to the .rmds

**Comment by CamFreshwater** [comment]
All three productivity OMs have the same alpha (only exception is on slide 17 where I showed an example of a low alpha, multivariate normal distribution). The greater uncertainty in the skew student-t distribution is due to the heavy tails, even though the medians are lower, you are more likely to get disproportionately large recruitment events than with the skewed normal. 

In terms of the spawner distributions, do you mean how the spawner distribution within a given trial within a given CU compares to the observed time series? If so, that will vary strongly among OMs, but I'm guessing it would be fairly similar in the reference productivity and reference sigma OM. Using a skewed student-t (particuarly with low synchrony) OR just ramping up sigma would result in more frequent spikes. Note, however, that we're still using the 3x maximum observed recruitment as a cap (i.e. they aren't allowed to **really** sky rocket).

**Comment by ann-marieH** [comment]
oop! I thought I'd provided a slide number ... I think it was slide 25-ish (one of the last slides), so SPN dist'n = spawner distribution over all of the simulations within a scenario?

Ah! I hadn't picked up on the fact that the skewed student-t ends up fattening up _both_ tails ... which I think answers my Q.

**Comment by CamFreshwater** [comment]
Yup that's the right slide, marking this closed for now!
